# Generated by Django 6.0 on 2026-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=255),
        ),
    ]
