# Generated by Django 6.0 on 2026-01-05 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AddField(
            model_name='guitar',
            name='string_num',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
