# Generated by Django 6.0 on 2026-01-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitar', to='products.brand'),
        ),
    ]
