# Generated by Django 6.0 on 2026-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_accessorytype_created_at_accessorytype_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorytype',
            name='accessory_type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
